repos:
  - repo: local
    hooks:
    - id: repo-agent
      name: RepoAgent
      entry: repoagent
      language: system
      pass_filenames: false # 阻止pre commit传入文件名作为参数
      # 可以指定钩子触发的文件类型，但是目前只支持python
      types: [python]